title = "Code Katas repo secret scanning rules"

[extend]
useDefault = true

[[allowlists]]
description = "Files to exclude from the scan"
paths = [
  '''(?i)(^|/)\.env\.example$''',
  '''(?i)(^|/)[^/]+\.env\.example$''',
  '''(^|/)node_modules(/|$)''',
  '''(^|/)pnpm-lock\.yaml$''',
  '''(^|/)dist(/|$)''',
  '''(^|/)build(/|$)'''
]

[[rules]]
id = "generic-secret-keywords"
description = "Detect common secret-related keywords"
regex = '''(?i)(password|passwd|pwd|secret|token|api[_-]?key|apikey|auth|credential|private[_-]?key|ssh[_-]?key|encryption[_-]?key)'''
secretGroup = 0
